M48
; DRILL file {KiCad 6.0.8-f2edbf62ab~116~ubuntu20.04.1} date Do 13 Okt 2022 01:57:36 CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-13T01:57:36+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.8-f2edbf62ab~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X3.5744Y-3.3545
X3.5744Y-3.5455
T2
X3.4551Y-3.3427
X3.4551Y-3.5573
T0
M30
